
//----------------------------------------------------
// The following code was generated by CUP v0.10k TUM Edition 20050516
// Fri Dec 13 16:30:49 CET 2019
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Dec_ComF = 37;
  public static final int AUTRE_VIDE = 44;
  public static final int programmer = 28;
  public static final int AG = 22;
  public static final int FSI = 4;
  public static final int OPERATION = 50;
  public static final int ALARME = 43;
  public static final int Dec_Com = 36;
  public static final int AD = 23;
  public static final int V = 16;
  public static final int EGAL = 19;
  public static final int Dec_AppF = 35;
  public static final int executer_scenario = 31;
  public static final int PG = 20;
  public static final int SI = 2;
  public static final int associer = 29;
  public static final int PD = 21;
  public static final int Dec_Sce = 40;
  public static final int message = 30;
  public static final int MOBILE = 14;
  public static final int DATE = 47;
  public static final int ScenarioF = 26;
  public static final int POINTV = 10;
  public static final int Dec_IntF = 39;
  public static final int definir = 27;
  public static final int CHAUFFAGE = 45;
  public static final int TELECOMMANDE = 13;
  public static final int CD = 24;
  public static final int DEGAL = 18;
  public static final int EOF = 0;
  public static final int ETAT = 51;
  public static final int FAIT = 8;
  public static final int FENETRE = 42;
  public static final int error = 1;
  public static final int Dec_SceF = 41;
  public static final int FAIRE = 7;
  public static final int POURTOUT = 5;
  public static final int IDF = 46;
  public static final int SINON = 6;
  public static final int Dec_Int = 38;
  public static final int ECLAIRAGE = 12;
  public static final int ALORS = 3;
  public static final int VOLET = 11;
  public static final int INTERRUPTEUR = 15;
  public static final int OPERATION_ET = 52;
  public static final int ProgD = 32;
  public static final int POINT = 9;
  public static final int ProgDF = 33;
  public static final int DPOINT = 17;
  public static final int ENTIER = 54;
  public static final int AUTRE = 49;
  public static final int CHAINE = 48;
  public static final int Dec_App = 34;
  public static final int Scenario = 25;
  public static final int APPR_DIST = 53;
}

